#! /bin/sh
#|
exec /scratch/cobbe/usr/bin/mzscheme -qu "$0" ${1+"$@"}
|#
(module run-admin-6 mzscheme 
  (require "administrate-tests-for-player-code.scm")
  ; (current-command-line-arguments (vector "harness-for-player" "TestVic"))

  (main  "administrate-tests-for-player <player> <test-directory>"))
	 
