#! /bin/sh
#|
exec /scratch/cobbe/usr/bin/mzscheme -qu "$0" ${1+"$@"}
|#
(module run-admin-7 mzscheme
  (require "administrate-tests-for-interact-code.scm")

  (main "administrate-tests-for-interact <interact module> <test-directory>"))
	 
  
